# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    
    # Run xcode tests and export as junit to be used by Gitlab
    scan(
      scheme: "SWC-iDPay-iOS",
      code_coverage: true,
      #clean: false,
      #skip_build: true,
      #testplan
      disable_slide_to_type: true,
      derived_data_path: './DerivedData', 
      output_directory: './sonar-reports',
      devices: 'iPhone 15 Pro'
    )
    
    # Evaluate test coverage (this is used by SonarQube)
    slather(
      build_directory: './DerivedData/Build',
      sonarqube_xml: true,
      output_directory: "sonar-reports",
      proj: "./SWC-iDPay-iOS.xcodeproj",
      scheme: "SWC-iDPay-iOS"
      #ignore:['../../*']
    )

    sonar

  end
end
