name: Pull request validation

on:
  pull_request:
    branches:
      - developer
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: PR title validation
        uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            docs
            refactor
            chore
            fix
            feat
            breaking
          requireScope: false
          subjectPattern: ^[A-Z].+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            doesn't match the configured pattern. Please ensure that the subject
            starts with an uppercase character.
          wip: false
