name: SonarQube Scan

on:
  push:
    branches:
      - developer

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v2.1.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: "https://sonarcloud.io:443"
      with:
        args: >
          -Dsonar.organization=pagopa
          -Dsonar.projectKey=pagopa_swc-idpay-ios
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.sources=./
          -Dsonar.test.exclusions=.swiftpm/**, .build/**, build/**, DerivedData/**/**, fastlane/**, *Tests/**, *Tests.*, sonar-reports/**, **/ComponentsDemoListView.swift, PagoPAUIKit/**
          -Dsonar.verbose=true
